definitions:
  steps:
    - step: &build-and-test
        name: Build and Test
        image: node:latest
        script:
          - echo 'Client Portal'

    - step: &build-and-deploy
        name: Build artifact
        image: node:18
        script:
          - yarn install
          - yarn build:web
          - pipe: atlassian/aws-s3-deploy:1.6.0
            variables:
              AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
              AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
              AWS_DEFAULT_REGION: "$AWS_REGION"
              S3_BUCKET: "${S3_BUCKET}"
              LOCAL_PATH: "dist/apps/web"
          - pipe: atlassian/aws-cloudfront-invalidate:0.10.0
            variables:
              AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID" 
              AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
              AWS_DEFAULT_REGION: "$AWS_REGION"
              DISTRIBUTION_ID: "$CF_DISTRIBUTION_ID"              


pipelines:
  default:
    - stage:
        name: Default Build and Test
        steps:
          - step: *build-and-test

  branches:
    develop:
      - stage:
          name: Deploy to Development
          deployment: Development          
          steps:
            - step: *build-and-deploy

    release/*:
      - stage:
          name: Deploy to QA
          deployment: QA
          steps:
            - step: *build-and-deploy

      - stage:
          name: Deploy to UAT
          deployment: UAT
          trigger: manual
          steps:
            - step: *build-and-deploy

      - stage:
          name: Deploy to Production
          deployment: Production
          trigger: manual
          steps:
            - step: *build-and-deploy
